cover = "https://i0.hdslb.com/bfs/album/c4fd60c326c24cd45624d5a434a9a77e07632a38.jpg"

[[4]]
type = "v_l"
ss = "19:23"
t = "00:58"
source = "https://b23.tv/ep409021"

[[6]]
type = "v_l"
ss = "20:28"
t = "00:13"
source = "https://b23.tv/ep409023"

[[9]]
type = "v_l"
ss = "14:19"
t = "00:16"
source = "https://b23.tv/ep409026"

[[9]]
type = "v_l"
ss = "14:26"
t = "02:35"
source = "https://b23.tv/ep409026"

[[10]]
type = "v_l"
ss = "08:53"
t = "00:03"
source = "https://b23.tv/ep409027"

[[12]]
type = "v_l"
ss = "18:30"
t = "00:03"
source = "https://b23.tv/ep409029"
