cover = "https://i0.hdslb.com/bfs/album/aec11553b3632e7ad163f9d89d4503d029076e5f.jpg"

[[4]]
type = "v_l"
ss = "12:02"
t = "00:31"
source = "https://b23.tv/ep417075"

[[4]]
type = "v_l"
ss = "12:55"
t = "01:38"
source = "https://b23.tv/ep417075"

[[5]]
type = "v_l"
ss = "06:46"
t = "00:10"
source = "https://b23.tv/ep417076"

[[5]]
type = "v_l"
ss = "08:51"
t = "00:13"
source = "https://b23.tv/ep417076"