cover="https://i0.hdslb.com/bfs/album/642eb9e6318a999fdfa10300ca6fc9e57e85d731.jpg"

[[1]]
type = "v_l"
ss = "11:04"
t = "00:13"
source = "https://b23.tv/ep409581"

[[4]]
type = "v_l"
ss = "09:52"
t = "00:05"
source = "https://b23.tv/ep409584"

[[4]]
type = "v_l"
ss = "14:52"
t = "00:32"
source = "https://b23.tv/ep409584"

[[4]]
type = "v_l"
ss = "14:53"
t = "00:09"
source = "https://b23.tv/ep409584"