cover="https://i0.hdslb.com/bfs/album/a83208ac5e240f2901eb1c588d51823ea89e3a46.jpg"

[[2]]
type = "v_l"
ss = "17:50"
t = "00:11"
source = "https://b23.tv/ep394429"

[[2]]
type = "v_l"
ss = "17:54"
t = "00:09"
source = "https://b23.tv/ep394429"

[[2]]
type = "v_l"
ss = "18:24"
t = "00:12"
source = "https://b23.tv/ep394429"

[[2]]
type = "s_l"
ss = "18:54"
t = "00:04"
source = "https://b23.tv/ep394429"

[[4]]
type = "v_l"
ss = "11:53"
t = "00:34"
source = "https://b23.tv/ep409967"