cover = "https://i0.hdslb.com/bfs/new_dyn/dcec858d9febfab5208d6ac296bbfed6512995925.jpg"

[[6]]
type = "v_l"
ss = "04:56"
t = "00:12"
source = "https://b23.tv/ep691417"

[[6]]
type = "s_l"
ss = "12:30"
t = "00:02"
source = "https://b23.tv/ep691417"

[[6]]
type = "v_c"
ss = "20:26"
t = ""
source = "https://b23.tv/ep691417"
