cover = "https://i0.hdslb.com/bfs/album/3f9f5bb651330b802e819e1b9988a0feeed5b7fb.jpg"

[[8]]
type = "s_l"
ss = "11:45"
t = "00:03"
source = "https://b23.tv/ep511498"

[[8]]
type = "s_c"
ss = "12:16"
t = ""
source = "https://b23.tv/ep511498"

[[8]]
type = "s_l"
ss = "13:38"
t = "00:04"
source = "https://b23.tv/ep511498"

[[8]]
type = "s_l"
ss = "12:52"
t = "00:04"
source = "https://b23.tv/ep511498"

[[8]]
type = "s_l"
ss = "17:04"
t = "00:03"
source = "https://b23.tv/ep511498"