cover = "https://i0.hdslb.com/bfs/album/288797d9dc9cb088b62a6c684bd46159f53f47f0.jpg"

[[15]]
type = "s_l"
ss = "18:37"
t = "00:05"
source = "https://b23.tv/ep691614"

[[20]]
type = "v_c"
ss = "00:06"
t = ""
source = "https://b23.tv/ep704873"

[[20]]
type = "s_l"
ss = "03:31"
t = "00:03"
source = "https://b23.tv/ep704873"

[[20]]
type = "v_l"
ss = "04:35"
t = "00:18"
source = "https://b23.tv/ep704873"