cover = "https://i0.hdslb.com/bfs/album/470017a40eacaa172bd11f2ab48d145049203c9d.jpg"

[[1]]
type = "v_l"
ss = "03:31"
t = "00:07"
source = "https://b23.tv/ep674245"

[[1]]
type = "v_l"
ss = "06:22"
t = "00:03"
source = "https://b23.tv/ep674245"

[[1]]
type = "v_c"
ss = "08:36"
t = ""
source = "https://b23.tv/ep674245"

[[1]]
type = "v_l"
ss = "17:46"
t = "00:07"
source = "https://b23.tv/ep674245"

[[1]]
type = "v_l"
ss = "19:07"
t = "00:04"
source = "https://b23.tv/ep674245"

[[2]]
type = "v_c"
ss = "13:10"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_c"
ss = "13:29"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "13:41"
t = "00:03"
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "13:46"
t = "00:03"
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "16:05"
t = "00:03"
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "16:10"
t = "00:04"
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "16:14"
t = "00:02"
source = "https://b23.tv/ep674246"

[[2]]
type = "s_c"
ss = "16:16"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_l"
ss = "16:35"
t = "00:02"
source = "https://b23.tv/ep674246"

[[2]]
type = "v_c"
ss = "16:45"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_c"
ss = "17:18"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_c"
ss = "17:24"
t = ""
source = "https://b23.tv/ep674246"

[[2]]
type = "v_c"
ss = "18:03"
t = ""
source = "https://b23.tv/ep674246"

[[3]]
type = "v_l"
ss = "00:24"
t = "00:03"
source = "https://b23.tv/ep674247"

[[3]]
type = "v_l"
ss = "03:14"
t = "00:02"
source = "https://b23.tv/ep674247"

[[3]]
type = "v_c"
ss = "04:27"
t = ""
source = "https://b23.tv/ep674247"

[[3]]
type = "v_c"
ss = "07:51"
t = ""
source = "https://b23.tv/ep674247"

[[3]]
type = "v_c"
ss = "08:16"
t = ""
source = "https://b23.tv/ep674247"

[[4]]
type = "v_l"
ss = "03:28"
t = "00:10"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "03:56"
t = "00:02"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "04:00"
t = "00:16"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "04:07"
t = "00:35"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_c s_c"
ss = "04:12"
t = ""
source = "https://b23.tv/ep674250"

[[4]]
type = "v_c"
ss = "05:19"
t = ""
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "06:13"
t = "00:32"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "15:06"
t = "00:13"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "15:09"
t = "00:03"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l v_c"
ss = "15:25"
t = "00:04"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "15:30"
t = "00:05"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "17:26"
t = "01:16"
source = "https://b23.tv/ep674250"

[[4]]
type = "v_l"
ss = "17:36"
t = "00:15"
source = "https://b23.tv/ep674250"

[[5]]
type = "v_l"
ss = "18:14"
t = "00:02"
source = "https://b23.tv/ep674251"

[[6]]
type = "v_l"
ss = "08:09"
t = "00:02"
source = "https://b23.tv/ep674252"

[[7]]
type = "v_l"
ss = "03:59"
t = "00:13"
source = "https://b23.tv/ep678946"

[[7]]
type = "v_l"
ss = "14:34"
t = "00:06"
source = "https://b23.tv/ep678946"

[[7]]
type = "v_l"
ss = "14:38"
t = "00:04"
source = "https://b23.tv/ep678946"

[[7]]
type = "s_c"
ss = "14:43"
t = ""
source = "https://b23.tv/ep678946"

[[7]]
type = "v_c"
ss = "15:11"
t = ""
source = "https://b23.tv/ep678946"

[[7]]
type = "v_c"
ss = "17:52"
t = ""
source = "https://b23.tv/ep678946"

[[9]]
type = "s_l"
ss = "12:08"
t = "00:04"
source = "https://b23.tv/ep678948"

[[9]]
type = "s_l"
ss = "12:11"
t = "00:03"
source = "https://b23.tv/ep678948"

[[13]]
type = "s_l"
ss = "07:18"
t = "00:02"
source = "https://b23.tv/ep691488"
