cover = "https://i0.hdslb.com/bfs/album/78e1af95bcf0c0079287c29a3da10d0018de00bd.jpg"

[[11]]
type = "v_l"
ss = "01:46"
t = "00:09"
source = "https://b23.tv/ep515119"

[[13]]
type = "v_l"
ss = "04:31"
t = "00:08"
source = "https://b23.tv/ep515121"

[[13]]
type = "v_l"
ss = "04:53"
t = "00:12"
source = "https://b23.tv/ep515121"

[[13]]
type = "v_l"
ss = "17:32"
t = "01:17"
source = "https://b23.tv/ep515121"