cover = "https://i0.hdslb.com/bfs/new_dyn/6eac0445e166fe52fa184a9ef642b1bf512995925.jpg"

[[7]]
type = "v_c"
ss = "18:00"
t = ""
source = "https://b23.tv/ep823828"
tips = ""
clip = ""

[[10]]
type = "v_c"
ss = "21:48"
t = ""
source = "https://b23.tv/ep825944"
tips = ""
clip = ""
