cover = "https://i0.hdslb.com/bfs/new_dyn/82def2b40688f4262a4a3c15d2234d6c512995925.jpg"

[[3]]
type = "v_l"
ss = "16:46"
t = "24"
source = "https://b23.tv/ep818698"
tips = ""
clip = ""

[[9]]
type = "v_l"
ss = "07:09"
t = "01:57"
source = "https://b23.tv/ep823282"
tips = ""
clip = ""

[[11]]
type = "v_l"
ss = "05:58"
t = "3"
source = "https://b23.tv/ep825565"
tips = ""
clip = ""

[[12]]
type = "v_l"
ss = "20:10"
t = "12"
source = "https://b23.tv/ep825566"
tips = ""
clip = ""
