cover = "https://i0.hdslb.com/bfs/new_dyn/6ac3f3154951673ee696c62e8314c790512995925.jpg"

[[1]]
type = "v_l"
ss = "08:38"
t = 19
source = "https://b23.tv/ep819775"

[[2]]
type = "v_l"
ss = "04:32"
t = 2
source = "https://b23.tv/ep819776"

[[2]]
type = "v_c"
ss = "04:35"
source = "https://b23.tv/ep819776"

[[2]]
type = "v_c"
ss = "07:17"
source = "https://b23.tv/ep819776"

[[2]]
type = "v_c"
ss = "09:52"
source = "https://b23.tv/ep819776"

[[3]]
type = "v_c"
ss = "11:50"
source = "https://b23.tv/ep819777"

[[3]]
type = "v_c s_c"
ss = "12:28"
source = "https://b23.tv/ep819777"

[[7]]
type = "v_c"
ss = "07:48"
source = "https://b23.tv/ep823819"

[[7]]
type = "s_c"
ss = "07:53"
source = "https://b23.tv/ep823819"

[[7]]
type = "s_c"
ss = "07:56"
source = "https://b23.tv/ep823819"

[[7]]
type = "v_c"
ss = "11:38"
source = "https://b23.tv/ep823819"

[[7]]
type = "v_l"
ss = "11:58"
t = 10
source = "https://b23.tv/ep823819"

[[7]]
type = "v_l"
ss = "14:24"
t = 8
source = "https://b23.tv/ep823819"

[[7]]
type = "s_l"
ss = "15:15"
t = 4
source = "https://b23.tv/ep823819"

[[7]]
type = "v_c"
ss = "15:21"
source = "https://b23.tv/ep823819"

[[7]]
type = "v_l"
ss = "19:25"
t = 19
source = "https://b23.tv/ep823819"

[[10]]
type = "v_l"
ss = "12:12"
t = 48
source = "https://b23.tv/ep825956"

[[10]]
type = "v_c"
ss = "13:42"
source = "https://b23.tv/ep825956"
