cover = "https://lain.bgm.tv/r/400/pic/cover/l/66/6d/397604_TgJ63.jpg"
tips = """
每周六更新。
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/06/亚托莉%20我挚爱的时光
"""

[[2]]
type = "v_l"
ss = "14:48"
t = 4
source = "https://b23.tv/ep828165"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "18:33"
t = 4
source = "https://b23.tv/ep828166"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "19:10"
t = 3
source = "https://b23.tv/ep828166"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "11:55"
t = 7
source = "https://b23.tv/ep831244"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "12:05"
t = 19
source = "https://b23.tv/ep831244"
clip = "TP-main::"

[["第06话"]]
type = "v_c"
ss = "12:04"
source = "https://b23.tv/ep831867"
clip = "TP-main::"
