cover = "https://lain.bgm.tv/r/400/pic/cover/l/e9/f4/478684_gVp0X.jpg"
tips = """
每周六更新。
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/06/天穗之咲稻姬
"""

[[1]]
type = "v_l"
ss = "13:18"
t = 3
source = "https://b23.tv/ep827859"
