cover = "https://lain.bgm.tv/r/400/pic/cover/l//0c/fd/428823_vuwNR.jpg"

[[2]]
type = "v_l"
ss = "09:14"
t = 4
source = "https://b23.tv/ep827156"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "04:46"
t = 5
source = "https://b23.tv/ep827157"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "21:46"
t = 13
source = "https://b23.tv/ep827157"
clip = "TP-main::"
