cover = "https://i0.hdslb.com/bfs/new_dyn/34194e6d865596880da37c74e4c71824512995925.jpg"

[[1]]
type = "v_c"
ss = "17:35"
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-17_35.mp4"

[[1]]
type = "s_l"
ss = "18:03"
t = 3
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-18_03.mp4"

[[1]]
type = "s_l"
ss = "18:24"
t = 4
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-18_24.mp4"

[[1]]
type = "v_l"
ss = "18:36"
t = 54
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-18_36.mp4"

[[1]]
type = "v_l"
ss = "18:40"
t = 10
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-18_40.mp4"

[[1]]
type = "v_l"
ss = "19:35"
t = 10
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-19_35.mp4"

[[1]]
type = "s_l"
ss = "21:21"
t = 2
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-21_21.mp4"

[[1]]
type = "s_l"
ss = "21:25"
t = 2
source = "https://b23.tv/ep827835"
clip = "https://alist.xrzyun.eu.org/aniclip-upload/2024.7/%E4%B8%8D%E6%97%B6%E7%94%A8%E4%BF%84%E8%AF%AD%E5%B0%8F%E5%A3%B0%E8%AF%B4%E7%9C%9F%E5%BF%83%E8%AF%9D%E7%9A%84%E9%82%BB%E6%A1%8C%E8%89%BE%E8%8E%89%E5%90%8C%E5%AD%A6/1-21_25.mp4"

[[2]]
type = "s_l"
ss = "07:30"
t = 4
source = "https://b23.tv/ep827836"

[[2]]
type = "v_l"
ss = "08:10"
t = 26
source = "https://b23.tv/ep827836"

[[2]]
type = "v_l"
ss = "08:15"
t = 4
source = "https://b23.tv/ep827836"

[[2]]
type = "v_l"
ss = "08:51"
t = 4
source = "https://b23.tv/ep827836"

[[2]]
type = "v_l"
ss = "13:27"
t = 8
source = "https://b23.tv/ep827836"

[[2]]
type = "s_l"
ss = "13:41"
t = 2
source = "https://b23.tv/ep827836"

[[2]]
type = "v_l"
ss = "18:50"
t = 16
source = "https://b23.tv/ep827836"

[[2]]
type = "v_c"
ss = "21:01"
source = "https://b23.tv/ep827836"
