cover = "https://i0.hdslb.com/bfs/new_dyn/4583de7d206cdf50bcf97cb25946e094512995925.jpg"

[[1]]
type = "s_l"
ss = "16:23"
t = "10"
source = "https://b23.tv/ep819339"
tips = ""
clip = ""

[[2]]
type = "v_l"
ss = "17:02"
t = "2"
source = "https://b23.tv/ep819340"
tips = ""
clip = ""

[[11]]
type = "v_l"
ss = "11:28"
t = "2"
source = "https://b23.tv/ep825965"
tips = ""
clip = ""
