cover = "https://lain.bgm.tv/r/400/pic/cover/l/32/fd/450586_FdLdq.jpg"
tips = """
每周五更新。
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/05/地下城中的人
"""

[[1]]
type = "v_c"
ss = "06:19"
source = "https://b23.tv/ep828473"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "06:38"
t = 2
source = "https://b23.tv/ep828473"
clip = "TP-main::"

[[2]]
type = "v_c"
ss = "12:16"
source = "https://b23.tv/ep828474"
clip = "TP-main::"

[[2]]
type = "v_c"
ss = "12:32"
source = "https://b23.tv/ep828474"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "12:00"
t = 2
source = "https://b23.tv/ep828475"
clip = "TP-main::"
