cover = "https://lain.bgm.tv/r/400/pic/cover/l//0c/fd/428823_vuwNR.jpg"
tips = """
原名：疑似后宫。
每周四更新。
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/04/疑似后宫
"""

[[2]]
type = "v_l"
ss = "09:14"
t = 4
source = "https://b23.tv/ep827156"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "04:46"
t = 5
source = "https://b23.tv/ep827157"
clip = "TP-main::"

[[3]]
type = "v_l"
ss = "21:46"
t = 13
source = "https://b23.tv/ep827157"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "06:16"
t = 2
source = "https://b23.tv/ep827158"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "06:23"
t = 24
source = "https://b23.tv/ep827158"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "11:32"
t = 8
source = "https://b23.tv/ep827158"
clip = "TP-main::"

[[5]]
type = "v_c v_l"
ss = "10:01"
t = 2
source = "https://b23.tv/ep827159"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "20:30"
t = 3
source = "https://b23.tv/ep827159"
clip = "TP-main::"

[[7]]
type = "v_l"
ss = "15:23"
t = 12
source = "https://b23.tv/ep827161"
clip = "TP-main::"
