cover = "https://i0.hdslb.com/bfs/new_dyn/34194e6d865596880da37c74e4c71824512995925.jpg"

[[1]]
type = "v_c"
ss = "17:35"
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "18:03"
t = 3
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "18:24"
t = 4
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "18:36"
t = 54
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "18:40"
t = 10
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "19:35"
t = 10
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "21:21"
t = 2
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "21:25"
t = 2
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[2]]
type = "s_l"
ss = "07:30"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:10"
t = 26
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:15"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:51"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "13:27"
t = 8
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "s_l"
ss = "13:41"
t = 2
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "18:50"
t = 16
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_c"
ss = "21:01"
source = "https://b23.tv/ep827836"
clip = "TP-main::"
