cover = "https://lain.bgm.tv/r/400/pic/cover/l/c9/4f/465884_fqZbB.jpg"
tips = """
每周二更新。
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/02/曾经、魔法少女和邪恶相互为敌。
"""

[[1]]
type = "v_l"
ss = "08:45"
t = 4
source = "https://b23.tv/ep830142"

[[2]]
type = "v_l"
ss = "05:48"
t = 6
source = "https://b23.tv/ep830143"

[[2]]
type = "v_l"
ss = "07:48"
t = 2
source = "https://b23.tv/ep830143"

[[2]]
type = "v_l"
ss = "07:55"
t = 8
source = "https://b23.tv/ep830143"

[[2]]
type = "v_c"
ss = "11:15"
source = "https://b23.tv/ep830143"

[[3]]
type = "v_c"
ss = "03:56"
source = "https://b23.tv/ep830144"

[[3]]
type = "v_l"
ss = "06:20"
t = 7
source = "https://b23.tv/ep830144"

[[3]]
type = "v_c"
ss = "06:33"
source = "https://b23.tv/ep830144"

[[4]]
type = "v_c"
ss = "03:45"
source = "https://b23.tv/ep830966"

[[5]]
type = "v_l"
ss = "00:45"
t = 5
source = "https://b23.tv/ep830967"

[[5]]
type = "v_l"
ss = "06:38"
t = 13
source = "https://b23.tv/ep830967"

[[6]]
type = "v_l"
ss = "00:38"
t = 4
source = "https://b23.tv/ep830968"

[[6]]
type = "v_l"
ss = "00:41"
t = 1
source = "https://b23.tv/ep830968"

[[6]]
type = "s_c"
ss = "03:53"
source = "https://b23.tv/ep830968"

[[6]]
type = "s_c"
ss = "05:52"
source = "https://b23.tv/ep830968"

[[6]]
type = "v_l"
ss = "08:00"
t = 6
source = "https://b23.tv/ep830968"

[[6]]
type = "s_c"
ss = "10:53"
source = "https://b23.tv/ep830968"
