cover = "https://lain.bgm.tv/r/400/pic/cover/l/7c/8e/424883_BpzVb.jpg"
tips = """
每周三更新，
观看：https://alist.xiaoya.pro/每日更新/动漫/日本/新番/03/不时轻声地以俄语遮羞的邻座艾莉同学
"""

[[1]]
type = "v_c"
ss = "17:35"
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "18:03"
t = 3
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "18:24"
t = 4
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "18:36"
t = 54
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "18:40"
t = 10
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "v_l"
ss = "19:35"
t = 10
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "21:21"
t = 2
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[1]]
type = "s_l"
ss = "21:25"
t = 2
source = "https://b23.tv/ep827835"
clip = "TP-main::"

[[2]]
type = "s_l"
ss = "07:30"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:10"
t = 26
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:15"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "08:51"
t = 4
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "13:27"
t = 8
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "s_l"
ss = "13:41"
t = 2
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_l"
ss = "18:50"
t = 16
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[2]]
type = "v_c"
ss = "21:01"
source = "https://b23.tv/ep827836"
clip = "TP-main::"

[[4]]
type = "s_l"
ss = "20:03"
t = 2
source = "https://b23.tv/ep829607"
clip = "TP-main::"

[[4]]
type = "v_l"
ss = "20:12"
t = 4
source = "https://b23.tv/ep829607"
clip = "TP-main::"

[[5]]
type = "v_l 4"
ss = "01:44"
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "03:15"
t = 117
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "04:01"
t = 47
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "04:08"
t = 19
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "s_l"
ss = "05:42"
t = 2
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_c"
ss = "07:10"
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "s_l"
ss = "07:36"
t = 2
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "10:12"
t = 10
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "10:25"
t = 14
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "10:46"
t = 2
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "10:50"
t = 3
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "11:27"
t = 5
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_l"
ss = "11:39"
t = 4
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[5]]
type = "v_c"
ss = "13:10"
source = "https://b23.tv/ep829608"
clip = "TP-main::"

[[6]]
type = "v_l"
ss = "04:10"
t = 21
source = "https://b23.tv/ep829609"
clip = "TP-main::"

[[6]]
type = "s_l"
ss = "04:32"
t = 3
source = "https://b23.tv/ep829609"
clip = "TP-main::"

[[6]]
type = "v_l"
ss = "15:05"
t = 8
source = "https://b23.tv/ep829609"
clip = "TP-main::"
