cover = "https://i0.hdslb.com/bfs/new_dyn/211f083bd07494761b1c1e132f72c3ba512995925.jpg"

[[1]]
type = "s_l"
ss = "12:08"
t = "1"
source = "https://b23.tv/ep819314"
tips = ""
clip = ""

[[3]]
type = "v_c"
ss = "05:20"
t = ""
source = "https://b23.tv/ep819316"
tips = ""
clip = ""

[[3]]
type = "v_l"
ss = "05:21"
t = "3"
source = "https://b23.tv/ep819316"
tips = ""
clip = ""


[[12]]
type = "v_c"
ss = "23:22"
source = "https://b23.tv/ep825575"
