title = "自动同步最新 | 声优广播的台词幕后 (更新中:06)"
cover = "https://i0.hdslb.com/bfs/new_dyn/fe7fb9c5f7a86fcf99f77d3893aee1b9512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第02话"]]
type = "s_l"
ss = "08:02"
t = 6
source = "https://b23.tv/ep818579"

[["第03话"]]
type = "v_l"
ss = "04:21"
t = 192
source = "https://b23.tv/ep818580"

[["第05话"]]
type = "v_l"
ss = "15:41"
t = 30
source = "https://b23.tv/ep820132"

[["第06话"]]
type = "v_l"
ss = "17:01"
t = 56
source = "https://b23.tv/ep820133"
