title = "自动同步最新 | 天穗之咲稻姬 (收录中：01)"
cover = "https://i0.hdslb.com/bfs/new_dyn/fe488ccbc97d6313b5fd4d1f74ec9ebc512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "v_l"
ss = "13:18"
t = 3
source = "https://b23.tv/ep827859"
