title = "自动同步最新 | 魔法少女与邪恶曾经敌对。 (new! 06)"
cover = "https://lain.bgm.tv/r/400/pic/cover/l/c9/4f/465884_fqZbB.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "v_l"
ss = "08:45"
t = 4
source = "https://b23.tv/ep830142"

[["第02话"]]
type = "v_l"
ss = "05:48"
t = 6
source = "https://b23.tv/ep830143"

[["第02话"]]
type = "v_l"
ss = "07:48"
t = 2
source = "https://b23.tv/ep830143"

[["第02话"]]
type = "v_l"
ss = "07:55"
t = 8
source = "https://b23.tv/ep830143"

[["第02话"]]
type = "v_c"
ss = "11:15"
source = "https://b23.tv/ep830143"

[["第03话"]]
type = "v_c"
ss = "03:56"
source = "https://b23.tv/ep830144"

[["第03话"]]
type = "v_l"
ss = "06:20"
t = 7
source = "https://b23.tv/ep830144"

[["第03话"]]
type = "v_c"
ss = "06:33"
source = "https://b23.tv/ep830144"

[["第04话"]]
type = "v_c"
ss = "03:45"
source = "https://b23.tv/ep830966"

[["第05话"]]
type = "v_l"
ss = "00:45"
t = 5
source = "https://b23.tv/ep830967"

[["第05话"]]
type = "v_l"
ss = "06:38"
t = 13
source = "https://b23.tv/ep830967"

[["第06话"]]
type = "v_l"
ss = "00:38"
t = 4
source = "https://b23.tv/ep830968"

[["第06话"]]
type = "v_l"
ss = "00:41"
t = 1
source = "https://b23.tv/ep830968"

[["第06话"]]
type = "s_c"
ss = "03:53"
source = "https://b23.tv/ep830968"

[["第06话"]]
type = "s_c"
ss = "05:52"
source = "https://b23.tv/ep830968"

[["第06话"]]
type = "v_l"
ss = "08:00"
t = 6
source = "https://b23.tv/ep830968"

[["第06话"]]
type = "s_c"
ss = "10:53"
source = "https://b23.tv/ep830968"
