title = "自动同步最新 | 亚托莉 -我挚爱的时光- (new! 04)"
cover = "https://lain.bgm.tv/r/400/pic/cover/l/66/6d/397604_TgJ63.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第02话"]]
type = "v_l"
ss = "14:48"
t = 4
source = "https://b23.tv/ep828165"

[["第03话"]]
type = "v_l"
ss = "18:33"
t = 4
source = "https://b23.tv/ep828166"

[["第03话"]]
type = "v_l"
ss = "19:10"
t = 3
source = "https://b23.tv/ep828166"

[["第04话"]]
type = "v_l"
ss = "11:55"
t = 7
source = "https://b23.tv/ep831244"

[["第04话"]]
type = "v_l"
ss = "12:05"
t = 19
source = "https://b23.tv/ep831244"
