title = "自动同步最新 | 摇曳露营△ 第三季 (已完结)"
cover = "https://i0.hdslb.com/bfs/new_dyn/6eac0445e166fe52fa184a9ef642b1bf512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第07话"]]
type = "v_c"
ss = "18:00"
source = "https://b23.tv/ep823828"

[["第10话"]]
type = "v_c"
ss = "21:48"
source = "https://b23.tv/ep825944"
