title = "自动同步最新 | 吹响吧！上低音号 第三季 (更新中:12)"
cover = "https://i0.hdslb.com/bfs/new_dyn/211f083bd07494761b1c1e132f72c3ba512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "s_l"
ss = "12:08"
t = 1
source = "https://b23.tv/ep819314"

[["第03话"]]
type = "v_c"
ss = "05:20"
source = "https://b23.tv/ep819316"

[["第03话"]]
type = "v_l"
ss = "05:21"
t = 3
source = "https://b23.tv/ep819316"

[["第12话"]]
type = "v_c"
ss = "23:22"
source = "https://b23.tv/ep825575"
