title = "自动同步最新 | 亦叶亦花 (new! 02)"
cover = "https://lain.bgm.tv/r/400/pic/cover/l/d5/89/464561_DRdV0.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "v_c"
ss = "08:02"
source = "https://b23.tv/ep827806"

[["第01话"]]
type = "v_l"
ss = "08:22"
t = 8
source = "https://b23.tv/ep827806"

[["第01话"]]
type = "v_l"
ss = "16:05"
t = 11
source = "https://b23.tv/ep827806"

[["第02话"]]
type = "v_l"
ss = "06:16"
t = 8
source = "https://b23.tv/ep829073"

[["第02话"]]
type = "v_l"
ss = "06:19"
t = 6
source = "https://b23.tv/ep829073"
