title = "自动同步最新 | 神渴望着游戏。 (更新中:12)"
cover = "https://i0.hdslb.com/bfs/new_dyn/82def2b40688f4262a4a3c15d2234d6c512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第03话"]]
type = "v_l"
ss = "16:46"
t = 24
source = "https://b23.tv/ep818698"

[["第09话"]]
type = "v_l"
ss = "07:09"
t = 117
source = "https://b23.tv/ep823282"

[["第11话"]]
type = "v_l"
ss = "05:58"
t = 3
source = "https://b23.tv/ep825565"

[["第12话"]]
type = "v_l"
ss = "20:10"
t = 12
source = "https://b23.tv/ep825566"
