title = "自动同步最新 | 怪兽8号 (更新中:04)"
cover = "https://i0.hdslb.com/bfs/new_dyn/95733b5ac8df68c344365938896e55f6512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "v_l"
ss = "02:01"
t = 2
source = "https://b23.tv/ep819571"

[["第01话"]]
type = "v_c"
ss = "06:36"
source = "https://b23.tv/ep819571"

[["第01话"]]
type = "v_c"
ss = "07:08"
source = "https://b23.tv/ep819571"

[["第02话"]]
type = "v_l"
ss = "10:31"
t = 1
source = "https://b23.tv/ep819572"

[["第02话"]]
type = "v_l"
ss = "13:02"
t = 1
source = "https://b23.tv/ep819572"

[["第03话"]]
type = "v_l"
ss = "17:26"
t = 1
source = "https://b23.tv/ep819573"

[["第03话"]]
type = "v_l"
ss = "19:19"
t = 6
source = "https://b23.tv/ep819573"

[["第04话"]]
type = "v_l"
ss = "15:52"
t = 2
source = "https://b23.tv/ep821140"

[["第04话"]]
type = "v_l"
ss = "15:56"
t = 5
source = "https://b23.tv/ep821140"

[["第04话"]]
type = "v_c"
ss = "16:22"
source = "https://b23.tv/ep821140"
