title = "自动同步最新 | 百变的七仓同学 (收录中：02)"
cover = "https://lain.bgm.tv/r/400/pic/cover/l//0c/fd/428823_vuwNR.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第02话"]]
type = "v_l"
ss = "09:14"
t = 4
source = "https://b23.tv/ep827156"
