title = "自动同步最新 | 夜晚的水母不会游泳 (已完结)"
cover = "https://i0.hdslb.com/bfs/new_dyn/81abc7dd9bbec1a9d49f0953d0059131512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "s_l"
ss = "01:41"
t = 2
source = "https://b23.tv/ep819318"

[["第01话"]]
type = "v_c"
ss = "01:55"
source = "https://b23.tv/ep819318"

[["第01话"]]
type = "v_c"
ss = "16:38"
source = "https://b23.tv/ep819318"

[["第02话"]]
type = "v_c"
ss = "03:12"
source = "https://b23.tv/ep819319"

[["第02话"]]
type = "s_l"
ss = "16:33"
t = 2
source = "https://b23.tv/ep819319"

[["第03话"]]
type = "v_c s_l"
ss = "11:32"
t = 2
source = "https://b23.tv/ep819320"

[["第04话"]]
type = "s_l"
ss = "06:33"
t = 16
source = "https://b23.tv/ep819850"

[["第04话"]]
type = "v_l"
ss = "10:15"
t = 35
source = "https://b23.tv/ep819850"

[["第05话"]]
type = "v_l"
ss = "21:44"
t = 7
source = "https://b23.tv/ep819320"

[["第06话"]]
type = "v_l"
ss = "10:31"
t = 25
source = "https://b23.tv/ep819852"

[["第06话"]]
type = "s_l"
ss = "12:06"
t = 3
source = "https://b23.tv/ep819852"

[["第06话"]]
type = "v_c"
ss = "16:23"
source = "https://b23.tv/ep819852"

[["第07话"]]
type = "v_l"
ss = "06:41"
t = 13
source = "https://b23.tv/ep823447"

[["第07话"]]
type = "s_l"
ss = "06:48"
t = 2
source = "https://b23.tv/ep823447"

[["第07话"]]
type = "v_l"
ss = "07:00"
t = 3
source = "https://b23.tv/ep823447"

[["第07话"]]
type = "v_l"
ss = "12:21"
t = 61
source = "https://b23.tv/ep823447"

[["第07话"]]
type = "v_l"
ss = "13:41"
t = 32
source = "https://b23.tv/ep823447"

[["第07话"]]
type = "v_c"
ss = "14:17"
source = "https://b23.tv/ep823447"

[["第08话"]]
type = "v_c"
ss = "05:56"
source = "https://b23.tv/ep823448"

[["第08话"]]
type = "v_l"
ss = "06:50"
t = 7
source = "https://b23.tv/ep823448"

[["第09话"]]
type = "v_c"
ss = "05:52"
source = "https://b23.tv/ep823449"

[["第09话"]]
type = "v_c"
ss = "23:23"
source = "https://b23.tv/ep823449"

[["第10话"]]
type = "v_c"
ss = "06:10"
source = "https://b23.tv/ep825188"

[["第11话"]]
type = "v_l"
ss = "02:36"
t = 6
source = "https://b23.tv/ep825189"

[["第11话"]]
type = "v_c"
ss = "09:56"
source = "https://b23.tv/ep825189"

[["第12话"]]
type = "v_l"
ss = "02:31"
source = "https://b23.tv/ep825190"

[["第12话"]]
type = "v_l 6s        20: 07"
ss = "16:30"
t = 6
source = "https://b23.tv/ep825190"
