title = "自动同步最新 | 亚托莉 -我挚爱的时光- new! 02"
cover = "https://lain.bgm.tv/r/400/pic/cover/l/66/6d/397604_TgJ63.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第02话"]]
type = "v_l"
ss = "14:48"
t = 4
source = "https://b23.tv/ep828165"
