title = "自动同步最新 | 不时用俄语小声说真心话的邻桌艾莉同学 (收录中:1)"
cover = "https://i0.hdslb.com/bfs/new_dyn/34194e6d865596880da37c74e4c71824512995925.jpg"
tips = "由自动程序从 hzj.wiki 同步而来，由于原站HTML问题，可能解析有误，请优先参考人工核准项目。"

[["第01话"]]
type = "v_c"
ss = "17:35"
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "s_l"
ss = "18:03"
t = 3
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "s_l"
ss = "18:24"
t = 4
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "v_l"
ss = "18:36"
t = 54
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "v_l"
ss = "18:40"
t = 10
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "v_l"
ss = "19:35"
t = 10
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "s_l"
ss = "21:21"
t = 2
source = "https://b23.tv/ep827835"

[["第01话"]]
type = "s_l"
ss = "21:25"
t = 2
source = "https://b23.tv/ep827835"
