cover = "https://i0.hdslb.com/bfs/new_dyn/xxxxxxxxx.jpg"

[[6]]
type = "v_l"
ss = "12:16"
t = "00:06"
source = "https://b23.tv/epxxxxx"

[[9]]
type = "v_l"
ss = "18:27"
t = "00:02"
source = "https://b23.tv/epxxxxx"
