name: Auto Sync Latest

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: ~

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    environment: action

    steps:
      - name: Generate a token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: "aniclip,aniclip-src"

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Sync from hzj.wiki
        run: |
          rm -rf ./AutoSyncLatest
          mkdir ./AutoSyncLatest
          deno run --allow-all ${{ vars.DENO_RUN_URL }}
          ls -la ./AutoSyncLatest

      - name: Update Submodules
        run: |
          git commit -a -S -m "docs: AutoSyncLatest from hzj.wiki"
          #git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
